---
- hosts: localhost
  vars:
    state: present
    s3_bucket: my-s3-bucket
    key: terraform.tfstate
    region: us-east-1
    app_env: dev
  tasks:
    - name: Run terraform script
      terraform:
        project_path: "./"
        state: "{{ state }}"
        backend_config:
          bucket: "{{s3_bucket}}"
          key: "{{key}}"
          region: "{{region}}"
        variables_file: "{{app_env}}.tfvars"
        workspace: "{{app_env}}"
